"""agrega creado_por a insumos

Revision ID: 076b5a3df9ce
Revises: 1e60d302573b
Create Date: 2026-03-25 19:53:58.547468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076b5a3df9ce'
down_revision = '1e60d302573b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_por', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_column('creado_por')

    # ### end Alembic commands ###
