"""crear tabla usuarios

Revision ID: 5305bbe3c8b4
Revises: 3cff253d4c62
Create Date: 2026-02-20 11:43:37.709436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5305bbe3c8b4'
down_revision = '3cff253d4c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.alter_column('iva',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('caducidad')
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('caducidad', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.alter_column('precio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.alter_column('iva',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)

    op.drop_table('usuarios')
    # ### end Alembic commands ###
