"""agregar correo y tipo_identificacion a clienteproveedor

Revision ID: c59a3f3c2dca
Revises: 4e679de5026f
Create Date: 2026-03-09 09:20:39.469918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59a3f3c2dca'
down_revision = '4e679de5026f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienteproveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_identificacion', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=True))
        batch_op.alter_column('nit',
               existing_type=sa.VARCHAR(length=15, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=1, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienteproveedor', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=1, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('nit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('correo')
        batch_op.drop_column('tipo_identificacion')

    # ### end Alembic commands ###
