"""agregar campos reset token a usuarios

Revision ID: d2cbdadb49ce
Revises: d2781bf85b01
Create Date: 2026-03-11 12:04:25.988842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cbdadb49ce'
down_revision = 'd2781bf85b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('numero_lote', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_compra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_entrada', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    op.drop_table('lotes')
    # ### end Alembic commands ###
