"""agregar id_usuario y nombre_usuario a movimientos

Revision ID: d7d680c8d2e7
Revises: 076b5a3df9ce
Create Date: 2026-03-25 20:39:52.076729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d680c8d2e7'
down_revision = '076b5a3df9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nombre_usuario', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_column('nombre_usuario')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
